stages:
  - deploy
  - test

deploy_job:
  stage: deploy
  when: always
  image: dvcorg/cml
  script:
    - cml-runner --cloud aws --cloud-region us-west --cloud-type g2.2xlarge
      --cloud-spot --labels=cml-runner-gpu

test_runner:
  stage: test
  when: on_success
  tags:
    - cml-runner-gpu
  script:
    - sudo update-alternatives --install /usr/bin/python python $(which python3)
      10
    - sudo apt-get update && sudo apt-get install -y python-pip python3-pip
    - sudo pip install --upgrade pip
    - sudo pip install --upgrade setuptools
    - sudo pip install tensorboard

    - npm ci
    - npm run lint
    - npm run test

    - nvidia-smi

test_container:
  stage: test
  when: on_success
  tags:
    - cml-runner-gpu
  image: dvcorg/cml-py3:latest
  script:
    - dvc --version
    - pip install tensorboard

    - npm ci
    - npm run lint
    - npm run test

    - nvidia-smi
